apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.appName}}-secret
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
{{- range $key, $value := .Values.jwtSecretData }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}